### ISSUE TITLE
5.12 branch is not available on flathub

### ISSUE THREAD

**Issue by coslyk** [flathub/io.qt.qtwebkit.BaseApp#12]
Hello,

I see that 5.12 branch has already been created here, but when I install it I got the error:
```
~$ flatpak install flathub io.qt.qtwebkit.BaseApp//5.12
error: Error searching remote flathub: Can't find ref io.qt.qtwebkit.BaseApp//5.12
```

**Comment by TingPing** [comment]
Rebuild: https://flathub.org/builds/#/buildrequests/40921?redirect_to_build=true

**Comment by coslyk** [comment]
Build fails here:
```
../Source/WebCore/bindings/js/JSDOMConstructor.h:195:35: error: invalid conversion from ‘JSC::EncodedJSValue (*)(JSC::ExecState*)’ {aka ‘long long int (*)(JSC::ExecState*)’} to ‘JSC::NativeFunction’ {aka ‘long long int (__attribute__((fastcall)) *)(JSC::ExecState*)’} [-fpermissive]
     constructData.native.function = construct;
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```

**Comment by eszlari** [comment]
Maybe we should just build x86_64 only. I don't think it's worth it and prevents us from moving a lot of apps to 5.12 (and freedesktop 18.08).

**Comment by TingPing** [comment]
https://flathub.org/builds/#/builders/32/builds/205

**Comment by Alexander-Wilms** [comment]
I can't install it on x64:

```
Multiple branches available for io.qt.qtwebkit.BaseApp, you must specify one of: io.qt.qtwebkit.BaseApp//5.11, io.qt.qtwebkit.BaseApp//5.9, io.qt.qtwebkit.BaseApp//stable
```

**Comment by aleixpol** [comment]
> Maybe we should just build x86_64 only. I don't think it's worth it and prevents us from moving a lot of apps to 5.12 (and freedesktop 18.08).

I tried building it in the server where we build our arm binaries. For aarch64 it built just fine and arm it failed with:

```
/usr/lib/gcc/arm-unknown-linux-gnueabihf/8.2.0/../../../../arm-unknown-linux-gnueabihf/bin/ld.gold: fatal error: lib/libQt5WebKit.so.5.212.0: mmap: failed to allocate 2809472916 bytes for output file: Cannot allocate memory
```

It could be interesting to see into linking without gold.

**Comment by TingPing** [comment]
> I can't install it on x64:

Because it wasn't published yet (things are delayed now).

https://flathub.org/builds/#/builders/29/builds/91

**Comment by TingPing** [comment]
I'll move the 32bit discussion since the issue of this version being published should be solved for now.

https://github.com/flathub/io.qt.qtwebkit.BaseApp/issues/14
