### ISSUE TITLE
Fails to build against 5.12 on 32bit arches

### ISSUE THREAD

**Issue by TingPing** [flathub/io.qt.qtwebkit.BaseApp#14]
It has been disabled for now but needs to be looked into.

Seems to be a linker memory issue:
```
/usr/lib/gcc/arm-unknown-linux-gnueabihf/8.2.0/../../../../arm-unknown-linux-gnueabihf/bin/ld.gold: fatal error: lib/libQt5WebKit.so.5.212.0: mmap: failed to allocate 2809472916 bytes for output file: Cannot allocate memory
```

**Comment by jurf** [comment]
This is actually blocking https://github.com/flathub/org.musescore.MuseScore/pull/20, hope it gets fixed soon.

**Comment by hfiguiere** [comment]
neither platforms are supported anymore.
