### ISSUE TITLE
Needs a rebuild

### ISSUE THREAD

**Issue by aleixpol** [flathub/io.qt.qtwebkit.BaseApp#16]
```
CMake Error at /usr/share/cmake-3.13/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  Could not find a configuration file for package "Qt5Widgets" that exactly
  matches requested version "5.12.1".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake, version: 5.12.2
    /lib/x86_64-linux-gnu/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake, version: 5.12.2

Call Stack (most recent call first):
  /app/lib/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsConfig.cmake:74 (find_dependency)
  CMakeLists.txt:76 (find_package)
```

We need to rebuild it every time upstream Qt is rebuilt, otherwise the minor version diverges.

**Comment by TingPing** [comment]
https://flathub.org/builds/#/builders/32/builds/1787

**Comment by TingPing** [comment]
Ugh the publish failed: https://flathub.org/builds/#/builders/29/builds/1776

**Comment by aleixpol** [comment]
We need to rebuild it for 5.12.3.

**Comment by jbruechert** [comment]
Until the rebuild is done this issue causes builds on the KDE Infrastructure and probably also flathub to fail (e.g https://binary-factory.kde.org/job/Trojita_flatpak/20/console).
With qmake, the webkit module does not depend on the exact patch release of Qt, maybe this is just incorrect in the cmake files and could be patched?

**Comment by TingPing** [comment]
https://flathub.org/builds/#/builders/32/builds/4672
