### ISSUE TITLE
Provide a 5.13 branch

### ISSUE THREAD

**Issue by jbruechert** [flathub/io.qt.qtwebkit.BaseApp#18]
Applications should migrate to org.kde.Sdk//5.13, which qtwebkit should do as well to make it possible for applications to update.

(This is supposed to be a tracking issue that applications can link to)

**Comment by TingPing** [comment]
Created; Lets see if it builds: https://flathub.org/builds/#/builders/32/builds/8658

EDIT: It does not build but failed at a, hopefully, simple step as it needs to use Python 3 now.

**Comment by barthalion** [comment]
Should be fixed with https://github.com/flathub/io.qt.qtwebkit.BaseApp/commit/403211b9e3693a6dbb347a42fd3b57b8e3351d0a. Build in progress: https://flathub.org/builds/#/builders/32/builds/9116

**Comment by jbruechert** [comment]
thanks!

**Comment by JBBgameich** [comment]
thanks!
