### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by eszlari** [flathub/io.qt.qtwebkit.BaseApp#2]
At the moment there is no cleanup section in the manifest. Since `io.atom.electron.BaseApp` and `org.electronjs.Electron2.BaseApp` have a cleanup step, I guess this is just based on a misunderstanding how cleanup in BaseApps works (I couldn't find anything in the documentation) and that the cleanup step is only performed when the final app is built.

**Comment by barthalion** [comment]
I have reverted your change. `cleanup` of the base application has absolutely no effect on the applications that are using it.

**Comment by eszlari** [comment]
Does this mean, it's not possible to cleanup unneeded files there?

**Comment by eszlari** [comment]
@barthalion Why do `io.atom.electron.BaseApp` and `org.electronjs.Electron2.BaseApp` include a cleanup step?

**Comment by barthalion** [comment]
Files from base applications are simply copied to resulting applications. There is no logic here. Electron base apps don't need development headers because we use both only for repackaged or downloaded via extra-data binary applications.

**Comment by eszlari** [comment]
I found out, that I can delete these files in the `post-install` step of the last module. Is this how it is supposed to work? Or is the an alternative?

**Comment by TingPing** [comment]
@eszlari Yes that works, cleanup not working is a bug: https://github.com/flatpak/flatpak/issues/1082

**Comment by nedrichards** [comment]
@barthalion fwiw we do use the Electron base apps for yarn and npm built applications, e.g. Sideka. https://github.com/flathub/id.sideka.App/blob/master/id.sideka.App.json

**Comment by TingPing** [comment]
Yes but `npm` doesn't often build native modules, so libs just dynamically load the libs at runtime only.

**Comment by nedrichards** [comment]
Absolutely.
