### ISSUE TITLE
Get 5.15 builds

### ISSUE THREAD

**Issue by aleixpol** [flathub/io.qt.qtwebkit.BaseApp#24]
The org.kde.Sdk//5.15 is available, we need to target it as well.

**Comment by jbruechert** [comment]
I tried to built QtWebKit with the 5.15 Sdk, and it seems to build fine already.
So it's likely just a matter of creating a new branch for it.

**Comment by eszlari** [comment]
ping @barthalion @TingPing

**Comment by barthalion** [comment]
https://flathub.org/builds/#/builders/32/builds/29327
