### ISSUE TITLE
Runtime 6.3

### ISSUE THREAD

**Issue by proletarius101** [flathub/io.qt.qtwebkit.BaseApp#27]
We need a 6.3 branch.

**Comment by proletarius101** [comment]
@hfiguiere

**Comment by hfiguiere** [comment]
there is not even a 6.2 branch.

**Comment by hfiguiere** [comment]
but I can help reviewing a PR and creating the branch from it.

**Comment by proletarius101** [comment]
I'm sorry, QtWebkit has been deprecated and is [removed](https://news.ycombinator.com/item?id=27696661) from Qt 6. So there will never be a 6.3 version for this repo.
